### ISSUE TITLE
Verbatim formatting

### ISSUE THREAD

**Issue by ggwpez** [sam0x17/docify#2]
Hey @sam0x17, I am looking at the docify output and wondered whether it would be possible to keep the original formatting.  
An [example](https://github.com/paritytech/substrate/blob/c72c7b7483038d0d5bd1ada5b4b3f388da9023f2/frame/migrations/src/tests.rs#L42) from Substrate:  
![image](https://github.com/sam0x17/docify/assets/10380170/43c8a4dd-e122-4ac6-aedf-fc5033df3d45)
vs
![image](https://github.com/sam0x17/docify/assets/10380170/a4d56d74-b668-4dfd-9467-a6c9eb669d82)

Would also be nice if doc comments stay in :smile:

**Comment by sam0x17** [comment]
Yeah right now we do a final pass using `prettyplease` because although it is grabbing source code from the original source, the indents of the leading attribute are usually incorrect. If I fix that properly, we can completely remove `prettyplease` and it should be exactly verbatim, so I'll see if I can get that working

**Comment by sam0x17** [comment]
Fixed, pushing a new version to crates.io in a sec:

![image](https://github.com/sam0x17/docify/assets/1855021/36be4846-2d12-432c-9b1f-d33d21a3dba4)

**Comment by sam0x17** [comment]
Fix was included in v0.1.15
